// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9vrQBQJJf0sZxmMrkB78fc8MuViu7DkE',
    appId: '1:775523371541:web:2a3b6edbe170e6573a9c1c',
    messagingSenderId: '775523371541',
    projectId: 'ultrafastsmm-b5f93',
    authDomain: 'ultrafastsmm-b5f93.firebaseapp.com',
    storageBucket: 'ultrafastsmm-b5f93.firebasestorage.app',
    measurementId: 'G-2LQ4D0KHZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3C-ZseOTXXSuT65osUV7QQZxRLaQbb6g',
    appId: '1:775523371541:android:d64032e51f6b4ac73a9c1c',
    messagingSenderId: '775523371541',
    projectId: 'ultrafastsmm-b5f93',
    storageBucket: 'ultrafastsmm-b5f93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJxYSjfJ4BHphZtL1ag2jLUkpd6H4SUNw',
    appId: '1:775523371541:ios:0a5ab5f9a537917e3a9c1c',
    messagingSenderId: '775523371541',
    projectId: 'ultrafastsmm-b5f93',
    storageBucket: 'ultrafastsmm-b5f93.firebasestorage.app',
    iosBundleId: 'com.example.ultrafastsmm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJxYSjfJ4BHphZtL1ag2jLUkpd6H4SUNw',
    appId: '1:775523371541:ios:0a5ab5f9a537917e3a9c1c',
    messagingSenderId: '775523371541',
    projectId: 'ultrafastsmm-b5f93',
    storageBucket: 'ultrafastsmm-b5f93.firebasestorage.app',
    iosBundleId: 'com.example.ultrafastsmm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9vrQBQJJf0sZxmMrkB78fc8MuViu7DkE',
    appId: '1:775523371541:web:84fc3345d88ab62f3a9c1c',
    messagingSenderId: '775523371541',
    projectId: 'ultrafastsmm-b5f93',
    authDomain: 'ultrafastsmm-b5f93.firebaseapp.com',
    storageBucket: 'ultrafastsmm-b5f93.firebasestorage.app',
    measurementId: 'G-N4T7WHE32W',
  );
}
